name: Deploy to Server

on:
  push:
    branches:
      - testEnv  # 當推送到 main 分支時觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # 檢出你的代碼

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 設定 Docker Buildx，這是構建 Docker 映像的工具

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}  # 伺服器的 IP 或域名
          username: ${{ secrets.SERVER_USER }}  # 伺服器的用戶名
          password: ${{ secrets.SERVER_PASSWORD }}  # 伺服器的 密碼
          script: |
            # 進入你的專案目錄
            cd C:\Users\1600620-17\Desktop\docker(ip cam)

            # 停止並移除現有的容器
            docker-compose down

            # 設定環境變數並啟動容器
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}

            # 從本地構建 Docker 映像並啟動容器
            docker-compose up --build -d  # 使用 --build 參數來強制重建映像

